"""生成 images/ 目录下的图片素材

使用 mmx image 生成 infographic 和 thumbnail。
"""
import json
import subprocess
from pathlib import Path
from datetime import datetime


def _get_data_for_image(game_id: str) -> dict:
    """从 output/{game_id}/data.json 读取数据"""
    output_dir = Path(f"output/{game_id}")
    data_path = output_dir / "data.json"
    if not data_path.exists():
        raise ValueError(f"data.json not found: {data_path}")
    return json.loads(data_path.read_text(encoding="utf-8"))


def _run_mmx_image(prompt: str, output_path: Path, aspect_ratio: str = "16:9") -> bool:
    """调用 mmx image generate 并保存到 output_path

    mmx 保存文件名为 {prefix}_001.jpg，需要重命名到目标路径。
    """
    output_path = output_path.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # mmx 生成的文件名是 {prefix}_001.jpg
    stem = output_path.stem  # 不含扩展名
    generated = output_path.parent / f"{stem}_001.jpg"

    try:
        result = subprocess.run(
            [
                "mmx", "image", "generate",
                "--prompt", prompt,
                "--out-dir", str(output_path.parent),
                "--out-prefix", stem,
                "--ar", aspect_ratio,
                "--quality", "2k",
                "--quiet",
            ],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode == 0:
            # 重命名到目标路径
            if generated.exists() and generated != output_path:
                generated.rename(output_path)
            print(f"  Generated: {output_path}")
            return True
        else:
            print(f"  mmx failed: {result.stderr[:200]}")
            return False
    except FileNotFoundError:
        print("  mmx not found - install with: npm install -g mmx-cli")
        return False
    except subprocess.TimeoutExpired:
        print("  mmx timeout")
        return False
    except Exception as e:
        print(f"  Error: {e}")
        return False


def generate_infographic(game_id: str, output_dir: Path):
    """
    生成评估曲线/失误分布 infographic.png

    使用 MiniMax 图片生成 API 创建专业的 chess infographic。
    包含：评估曲线走势 + 失误分布 + 关键数据
    """
    data = _get_data_for_image(game_id)

    images_dir = output_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)
    output_path = images_dir / "infographic.jpg"

    # 构建英文 prompt（让 AI 模型更好理解）
    white = data.get("white", "?")
    black = data.get("black", "?")
    result = data.get("result", "?")
    opening = data.get("opening", "Chess").split(",")[0].split("Game")[0].strip()
    highlights = data.get("highlights", [])
    blunders = data.get("blunders", [])

    # 提取妙着
    my_highlights = [h for h in highlights if h.get("side") == "white"]
    my_blunders = [b for b in blunders if b.get("side") == "white"]

    # 最佳妙着
    best_highlight = my_highlights[0] if my_highlights else None
    best_highlight_text = f"+{best_highlight['eval']:.2f}" if best_highlight else "N/A"
    # 最严重失误
    worst_blunder = my_blunders[0] if my_blunders else None
    worst_blunder_text = f"-{abs(worst_blunder['eval_drop']):.1f}" if worst_blunder else "N/A"

    prompt = f"""Professional chess analysis infographic in Bloomberg/Financial Times dark blue style.

Layout: Dark navy background (#1a1a2e), gold accents (#e6b800).

Top banner: "♔ ChessLens | {white} vs {black}"
Subtitle: "{opening} | Result: {result}"

Left panel - "Evaluation Timeline":
- Simple line chart showing game progression
- White line for white's evaluation
- Key moments marked with dots

Right panel - "Key Statistics":
- Best move: {best_highlight['san'] if best_highlight else 'N/A'} ({best_highlight_text})
- Worst mistake: {worst_blunder['san'] if worst_blunder else 'N/A'} ({worst_blunder_text} pawns)
- Total mistakes: {len(my_blunders)}

Bottom: "Generated by ChessLens AI" | {data.get('date', '')}

Clean, minimal, data-journalism aesthetic. No photos. Chinese chess symbols optional."""
    prompt = prompt.replace("\n", " ").strip()

    ok = _run_mmx_image(prompt, output_path, aspect_ratio="16:9")
    if not ok:
        # fallback: create placeholder
        _create_infographic_placeholder(images_dir, data)


def generate_thumbnail(game_id: str, output_dir: Path):
    """
    生成视频封面 thumbnail.jpg

    封面风格：戏剧性、有悬念、吸引点击
    """
    data = _get_data_for_image(game_id)

    images_dir = output_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)
    output_path = images_dir / "thumbnail.jpg"  # mmx outputs jpg

    white = data.get("white", "?")
    black = data.get("black", "?")
    opening = data.get("opening", "Chess").split(",")[0].strip()
    my_blunders = [b for b in data.get("blunders", []) if b.get("side") == "white"]
    worst = my_blunders[0] if my_blunders else None

    result = data.get("result", "?")

    # 戏剧性标题
    if "1-0" in result:
        outcome_text = "险胜！"
        mood = "dramatic victory"
    elif "0-1" in result:
        outcome_text = "惜败"
        mood = "tough loss"
    else:
        outcome_text = "弈和"
        mood = "drawn"

    prompt = f"""YouTube/小红书 video thumbnail for chess game review.

Design: Bold, dramatic, high contrast.
- Dark blue gradient background
- Large Chinese text overlay: "{white} vs {black}"
- Subtitle: "{opening} | {outcome_text}"
- Bottom text: "♔ Chess Review | AI Analysis"

Font: Bold, clean sans-serif, large text (takes 40% of image).
No actual chess board visible.
Cinematic lighting effect, elegant.

Aspect ratio 16:9."""
    prompt = prompt.replace("\n", " ").strip()

    ok = _run_mmx_image(prompt, output_path, aspect_ratio="16:9")
    if not ok:
        _create_thumbnail_placeholder(images_dir)


def _create_infographic_placeholder(images_dir: Path, data: dict):
    """创建 infographic 占位文本文件"""
    p = images_dir / "infographic_placeholder.txt"
    p.write_text(
        f"Infographic placeholder - game {data.get('game_id')}\n"
        f"Date: {data.get('date')}\n"
        f"White: {data.get('white')} | Black: {data.get('black')}\n"
        f"Result: {data.get('result')}\n"
        f"Highlights: {len(data.get('highlights', []))}\n"
        f"Blunders: {len(data.get('blunders', []))}\n"
        f"mmx image generation failed - check API key",
        encoding="utf-8"
    )
    print(f"  Infographic placeholder created")


def _create_thumbnail_placeholder(images_dir: Path):
    """创建 thumbnail 占位文件"""
    p = images_dir / "thumbnail_placeholder.txt"
    p.write_text(
        f"Thumbnail placeholder\n"
        f"mmx image generation failed - check API key",
        encoding="utf-8"
    )
    print(f"  Thumbnail placeholder created")


def write_board_screenshot(game_id: str, output_dir: Path):
    """将棋盘截图复制到 output/images/board.png"""
    possible_sources = [
        Path(f"docs/reviews/images/{game_id}.png"),
        Path(f"docs/reviews/images/{game_id.split('_')[1] if '_' in game_id else game_id}.png"),
        Path(f"~/chessLens/chess-reviews-summary/images/{game_id}.png").expanduser(),
    ]

    images_dir = output_dir / "images"
    images_dir.mkdir(parents=True, exist_ok=True)

    for src in possible_sources:
        if src.exists():
            dst = images_dir / "board.png"
            dst.write_bytes(src.read_bytes())
            print(f"  Board screenshot: {src} -> {dst}")
            return dst

    p = images_dir / "board_placeholder.txt"
    p.write_text(f"Board screenshot for {game_id} not found", encoding="utf-8")
    print(f"  Board screenshot not found")
    return p


def write_blunder_images(game_id: str, output_dir: Path):
    """复制失误对比图"""
    actual_game_id = game_id.split("_")[1] if "_" in game_id else game_id
    images_dir = Path("docs/reviews/images")
    output_images = output_dir / "images"
    output_images.mkdir(parents=True, exist_ok=True)

    copied = []
    if images_dir.exists():
        for img_file in images_dir.iterdir():
            if actual_game_id in img_file.name and "blunder" in img_file.name:
                dst = output_images / img_file.name
                dst.write_bytes(img_file.read_bytes())
                copied.append(dst)
    return copied